services:
  comfyui:
    image: ghcr.io/burritocatai/comfyui:v0.3.10-cuda-12.4.0
    container_name: comfyui
    hostname: "comfyui"
    networks:
      - ai-apps
    volumes:
      - "comfyui_models:/comfyui/ComfyUI/models"
      - "comfyui_nodes:/comfyui/ComfyUI/custom_nodes"
      - "comfyui_output:/comfyui/ComfyUI/output"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  sdnext:
    container_name: "sdnext"
    hostname: "sdnext"
    image: ghcr.io/burritocatai/sdnext:cuda-12.4.0
    networks:
      - ai-apps
    volumes:
      - "comfyui_models:/sdnext/automatic/models"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    command:
      - "serve"
    container_name: "ollama"
    hostname: "ollama"
    image: "ollama/ollama:0.5.5"
    networks:
      - ai-apps
    volumes:
      - "ollama:/root/.ollama"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  openui:
    container_name: openui
    hostname: "openui"
    image: "ghcr.io/open-webui/open-webui:main"
    networks:
      - ai-apps
    volumes:
      - "openwebui:/app/backend/data"

networks:
  ai-apps:
    external: true

volumes:
  comfyui_models:
    external: true
  comfyui_nodes:
    external: true
  comfyui_output:
    external: true
  ollama:
    external: true
  openwebui:
    external: true