services:
  gitea:
    container_name: "gitea"
    hostname: "gitea"
    image: "gitea/gitea:latest"
    networks:
      - dev-apps
    ports:
      - "3000:3000/tcp"
    volumes:
      - "gitea_data:/data"

networks:
  dev-apps:
    external: true

volumes:
  gitea_data:
    external: true
