services:
  gitea:
    container_name: "gitea"
    hostname: "gitea"
    image: "gitea/gitea:latest"
    networks:
      - dev-apps
    ports:
      - "3000:3000/tcp"
    volumes:
      - "gitea_data:/data"

  nifi:
    container_name: "nifi"
    hostname: "nifi"
    image: "apache/nifi:2.1.0"
    networks:
      - dev-apps
    environment:
      - NIFI_WEB_HTTPS_PORT=9943
      - NIFI_WEB_HTTPS_HOST=nifi
      - NIFI_WEB_PROXY_HOST=${NIFI_PROXY_HOSTS:-nifi,nifi:9443}
      - NIFI_WEB_PROXY_CONTEXT_PATH=/
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_ADMIN_USER:-admin}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_ADMIN_PASS:-admin1234567890}
    ports:
      - "9943:9943/tcp"
    volumes:
      - "nifi_conf:/opt/nifi/nifi-current/conf"
      - "nifi_cr:/opt/nifi/nifi-current/content_repository"
      - "nifi_fr:/opt/nifi/nifi-current/flowfile_repository"
      - "nifi_dr:/opt/nifi/nifi-current/database_repository"
      - "nifi_pr:/opt/nifi/nifi-current/provenance_repository"
      - "nifi_logs:/opt/nifi/nifi-current/logs"
      - "nifi_state:/opt/nifi/nifi-current/state"



#  nifi-registry:
#    container_name: "nifi-registry"
#    hostname: "nifi-registry"
#    image: "apache/nifi-registry:2.1.0"
#    networks:
#      - dev-apps
#    ports:
#      - "18080:18080/tcp"
#    volumes:
#      - "nifi_registry_data:/opt/nifi-registry/nifi-registry-current/data"

networks:
  dev-apps:
    external: true

volumes:
  gitea_data:
    external: true
  # nifi_registry_data:
  #   external: true
  nifi_conf:
    external: true
  nifi_cr:
    external: true
  nifi_fr:
    external: true
  nifi_dr:
    external: true
  nifi_pr:
    external: true
  nifi_logs:
    external: true
  nifi_state:
    external: true